### PR TITLE
Add basic shibboleth authentication plugin

### PR DESCRIPTION
**Pull request by cpockett**
Adds basic shibboleth plugin for authentication, assumes using lazy shibboleth but will work with active.  
Created based on shibboleth code from Micheal Berkowski @mberkowski.

This is my first pull-request on github so apologies about any issues.

### CODE REVIEW

**Comment by mberkowski** [comment]
Thanks @cpockett! I'll spend some time reviewing this, though possibly not until next week. I may look at encapsulating the plugin-specific config somehow, or cooking up a quick mechanism for plugins to report what config they require. It's just never come up before because no one contributed any.  Feel free to ping me if you don't hear anything about this and a couple of weeks have passed.

**Comment by cpockett** [comment]
Yeah I was looking for a good way to encapsulate plugin-specific config as it would make me happier with it. I'm going to make an update for it to fix the Lazy vs Active mode options. I called it guest mode which was ambiguous and could use a few more fixes to run smoothly in Active mode.

**Comment by cpockett** [comment]
Should be good now. Let me know what you think when you get a chance. I'm up for ideas for ways to make it work better. I'm using a customized version of this at the University of Saskatchewan Library currently and it's holding up well.

**Comment by mberkowski** [comment]
Thanks @cpockett, I've merged this as submitted. I did create #5 as a future enhancement but I don't have the time to really work it out right now and what you've contributed is more than sufficient.

**Pull request merged**
